# Generated by Django 3.2.15 on 2022-08-24 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20220824_2148'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductModel',
            new_name='ProductsModel',
        ),
    ]
