# Generated by Django 3.2.15 on 2022-08-25 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_productmodel_productsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsmodel',
            name='image_name',
        ),
    ]
