# Generated by Django 3.2.15 on 2022-08-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_productsmodel_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
