# Generated by Django 3.2.15 on 2022-08-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productsmodel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='bathroom_count',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='room_count',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='square_meters',
            field=models.FloatField(null=True),
        ),
    ]
