# Generated by Django 3.2.15 on 2022-08-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20220825_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='property_type',
            field=models.CharField(choices=[('Apartment', 'apartment'), ('House', 'house'), ('Studio', 'studio')], default='Apartment', max_length=9),
        ),
    ]
