# Generated by Django 3.2.15 on 2022-08-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_productsmodel_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='property_type',
            field=models.CharField(choices=[('For Sell', 'sell'), ('For Rent', 'rent')], default='For Sell', max_length=8),
        ),
    ]
