# Generated by Django 3.2.15 on 2022-08-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_rename_images_productsmodel_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
