# Generated by Django 3.2.15 on 2022-08-26 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_productsmodel_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsmodel',
            old_name='property_value',
            new_name='property_feature',
        ),
    ]
